"""Write docs/device-icons.svg from the drawings the bridge itself uses.

The geometry lives in sonosbridge/deviceicons.py - the bridge rasterises it for
the icons it serves over UPnP, and this script writes the same outlines out as
an SVG sprite for the documentation.  Run it after changing a device's shape:

    python tools/gen_device_icons.py docs/device-icons.svg
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from sonosbridge.deviceicons import ICON_NAMES, VIEW, svg_paths  # noqa: E402

SPRITE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Sonos device line icons. Generated by tools/gen_device_icons.py from
     sonosbridge/deviceicons.py - edit the outlines there, not the path data
     here.
     Inline this sprite (or copy a symbol's paths) and draw one with
     <use href="#i-arc"/>; fill, stroke, stroke-width and the cap/join style
     are inherited properties, so the host <svg> sets colour and weight. -->
<svg xmlns="http://www.w3.org/2000/svg" width="0" height="0"
     fill="none" stroke="currentColor" stroke-width="1.1"
     stroke-linecap="round" stroke-linejoin="round">
  <defs>
{symbols}
  </defs>
</svg>
"""


def symbol(name: str) -> str:
    size = int(VIEW)
    paths = "".join(f'\n      <path d="{d}"/>' for d in svg_paths(name))
    return f'    <symbol id="i-{name}" viewBox="0 0 {size} {size}">{paths}\n    </symbol>'


def main(argv: list[str]) -> None:
    sprite = SPRITE.format(symbols="\n".join(symbol(name) for name in ICON_NAMES))
    if len(argv) > 1:
        pathlib.Path(argv[1]).write_text(sprite, encoding="utf-8")
    else:
        sys.stdout.write(sprite)


if __name__ == "__main__":
    main(sys.argv)
